Add permission for elasticsearchversion.
kubeware/installer pull request #10
Opened 2023-09-06 12:12 UTC by pritamdas99

Signed-off-by: Pritam <pritam@appscode.com>

2023-09-06 12:43 UTC, AbdullahAlShaad approved these changes
LGTM!

2023-09-07 05:32 UTC, ArnobKumarSaha requested changes

2023-09-07 05:32 UTC, ArnobKumarSaha commented on charts/catalog-manager/templates/cluster-role.yaml
> +  - elasticsearchversions
remove.  `elasticsearchversions` is not in kubedb.com group

2023-09-07 05:32 UTC, ArnobKumarSaha commented on charts/catalog-manager/templates/cluster-role.yaml
> +  verbs: [ "*" ]
Why `*` permission is needed ? get-list-watch should be enough.

2023-09-07 05:44 UTC, ArnobKumarSaha requested changes

2023-09-07 05:44 UTC, ArnobKumarSaha commented on charts/catalog-manager/templates/cluster-role.yaml
> +  verbs: [ "get","list","watch" ]
Combine serviceaccounts & secrets together. As they are in same apiGroup & same level of permission.

2023-09-07 06:13 UTC, ArnobKumarSaha approved these changes

2023-09-07 06:46 UTC, merged